language: objective-c

branches:
 only:
 - master

xcode_project: MPGSDK.xcodeproj
xcode_scheme: MPGSDK-iOS
osx_image: xcode10.1
xcode_sdk: iphonesimulator10.1

script:
- xcodebuild clean build test -workspace MPGSDK.xcworkspace -scheme MPGSDK-iOS -destination "platform=iOS Simulator,name=iPhone X"
